# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 90d2af31fb7ea9dffaa1668569c9f6e519ba3af722ae4b32d9a5246768713929bb1af1ae05e200f22e94599ea136522e892836d30514af5bac225f897c9065dc

test:
  secret_key_base: a15f974079cdba2bc45f6c2e8130707d2525a2326e91959cba2c2713e866df5a64a88b12a54dce19bee3cf6300048ebce65a1b3c2bcc2589e5eb08a82b731f32

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
